changed yml file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,19 +1,13 @@
 name: CI/CD
-
 on: push
-
 jobs:
- build:
-   runs-on: ubuntu-latest
-
-   steps: 
-    - uses: actions/checkout@v2
-
-    - name: Run a one-line script
-    run: echo "Hello, CI/CD!"
-
-     #- name: Simulate an error
-     #  run: echo "About to fail" ; exit 1
-
-     #- name: Another greeting
-     #  run: echo "Hello, CI/CD again!"
+build:
+runs-on: ubuntu-latest
+steps:
+- uses: actions/checkout@v2
+- name: Run a one-line script
+run: echo "Hello, CI/CD!"
+#- name: Simulate an error
+# run: echo "About to fail" ; exit 1
+#- name: Another greeting
+# run: echo "Hello, CI/CD again!"
